name: listenable_generator
description: Source code generator to make you models changes listenable by flutter widgets using ValueListenableBuilder, it processes @ListenableModel and @ListenableProperty annotations.
version: 0.3.0
author: Camilo Alvarez <cadorca@gmail.com>
homepage: https://github.com/cadorca/listenable

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.1
  analyzer: ^0.37.0
  listenable: ^0.3.0

dev_dependencies:
  build_test: ^0.10.8
  build_runner: ^1.1.0
  test: ^1.0.0